<?php

namespace GeekHub\ShopBundle\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * ManufacturerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ManufacturerRepository extends EntityRepository
{
    public function getAllOrderByName()
    {
        return $this->createQueryBuilder('m')
            ->orderBy('m.name', 'ASC')
            ->getQuery()
            ->getResult();
    }
}
