<?php

namespace GeekHub\ShopBundle\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends EntityRepository
{
    function getAllProductsOrderByName()
    {
        $query = $this->createQueryBuilder('prod')
            ->orderBy('prod.name', 'ASC')
            ->getQuery();

        return $query->getArrayResult();
    }
}
